//===- SemanticsEmitter.cpp - Generate a Instruction Set Desc. ------------===//
//
//                     The LLVM Compiler Infrastructure
//
// This file is distributed under the University of Illinois Open Source
// License. See LICENSE.TXT for details.
//
//===----------------------------------------------------------------------===//
//
// This tablegen backend is responsible for emitting a description of the
// instruction-level semantics of the target instruction set.
//
//===----------------------------------------------------------------------===//

#include "CodeGenDAGPatterns.h"
#include "CodeGenTarget.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/Support/PrettyStackTrace.h"
#include "llvm/Support/Signals.h"
#include "llvm/TableGen/Record.h"
#include "llvm/TableGen/TableGenBackend.h"
#include <algorithm>
#include <map>

using namespace llvm;

namespace {

/// The target we're generating semantics for: keeps around some useful
/// references to the parsed CodeGen target description, and some generation
/// variables.
class SemanticsTarget {
public:
  RecordKeeper &Records;
  CodeGenDAGPatterns CGPatterns;
  CodeGenTarget &CGTarget;

  /// Keep track of the equivalence between target-specific SDNodes and
  /// their target-independent equivalent, as described in definitions
  /// derived of the SDNodeEquiv class.
  DenseMap<Record *, Record *> SDNodeEquiv;

  /// Unique constant integers, keeping track of the order they appeared in.
  /// This is done so that the generated semantics table is an unsigned[],
  /// with uint64_t constants only being an unsigned index to this table.
  /// Use an std::map instead of:
  /// - SetVector, because knowing whether a key exists isn't enough,
  ///   we also need an efficient way to get its index.
  /// - DenseMap, because there is no acceptable tombstone key.
  /// There is no element at index 0.
  std::map<uint64_t, unsigned> ConstantIdx;
  unsigned CurConstantIdx;

  SemanticsTarget(RecordKeeper &Records);
};

/// The semantics of a single SDNode, as an operation, taking operands and
/// producing typed results.
class NodeSemantics {
public:
  /// The opcode for this operation: either an ISD (for SDNodes), or DCINS
  /// (for other operations, like manipulating operands, registers, etc..)
  /// opcode.
  StringRef Opcode;

  /// The types of each result generated by this operation.
  std::vector<MVT::SimpleValueType> Types;

  /// All the operands of this instruction.
  std::vector<std::string> Operands;

  void addOperand(StringRef Op) { Operands.push_back(Op); }
};

class InstSemantics {
public:
  std::vector<NodeSemantics> Semantics;

  /// Construct semantics for the pattern \p TP, for instruction \p CGI.
  InstSemantics(SemanticsTarget &Target, const CodeGenInstruction &CGI,
                const TreePattern &TP);
  /// Default constructor for empty semantics.
  InstSemantics();
};

/// The core of the Pattern->Semantics translation, the "flattener".
class Flattener {
public:
  Flattener(SemanticsTarget &Target, const CodeGenInstruction &CGI,
            InstSemantics &I)
      : Target(Target), CGI(CGI), I(I), CurDefNo(0) {}

private:
  SemanticsTarget &Target;
  const CodeGenInstruction &CGI;
  InstSemantics &I;

  SmallPtrSet<Record *, 1> EliminatedImplicitRegs;
  StringMap<unsigned> OperandByName;

  unsigned CurDefNo;

  /// Get the CodeGenInstruction OperandInfo for \p Name.
  const CGIOperandList::OperandInfo *getNamedOperand(StringRef Name) {
    if (Name.empty())
      return nullptr;
    // FIXME: This is the slow, stupid, simple way.
    for (auto &Op : CGI.Operands)
      if (Name == Op.Name)
        return &Op;
    return nullptr;
  }

  /// Set the types of \p NS to what was inferred for \p TPN, or MVT::isVoid if
  /// the node has no result.
  void setNSTypeFromNode(NodeSemantics &NS, const TreePatternNode *TPN) {
    if (TPN->getNumTypes()) {
      for (auto &Ty : TPN->getExtTypes())
        NS.Types.push_back(Ty.getConcrete());
    } else {
      NS.Types.push_back(MVT::isVoid);
    }
  }

  /// Add the operation \p NS to the instruction semantics, keeping track of
  /// the defined values.
  void addSemantics(const NodeSemantics &NS) {
    for (auto &Ty : NS.Types)
      if (Ty != MVT::isVoid)
        ++CurDefNo;
    I.Semantics.push_back(NS);
  }

  /// Add the results of \p Prev as operands to \p NS.
  void addResOperand(NodeSemantics &NS, const NodeSemantics &Prev) {
    unsigned FirstDefNo = CurDefNo - (Prev.Types.size() - 1);
    for (unsigned i = 0, e = Prev.Types.size(); i != e; ++i) {
      if (Prev.Types[i] != MVT::isVoid)
        NS.addOperand(utostr(FirstDefNo + i));
    }
    addSemantics(Prev);
  }

  /// Make node semantics from an Operand patern:
  /// - if \p TPN is a RegisterClass or a RegisterOperand, generate:
  ///     DCINS::GET_RC, <inferred type>, <MIOperandNo of the Operand>
  /// - if \p TPN is an Operand, generate:
  ///     DCINS::CUSTOM_OP, <inferred types>,
  ///       <the Operand type as a Target::OpTypes:: enum value>,
  ///       <MIOperandNo of the first MI operand for this Operand>
  /// - if \p TPN is an OPERAND_IMMEDIATE Operand, generate:
  ///     DCINS::CONSTANT_OP, <inferred type>, <MIOperandNo of the Operand>
  ///
  /// Also, add the values defined by this node as operands to \p Parent.
  ///
  void flattenOperand(const TreePatternNode *TPN, NodeSemantics *Parent,
                      const CGIOperandList::OperandInfo *OpInfo) {
    Record *OpRec = OpInfo->Rec;
    NodeSemantics Op;
    setNSTypeFromNode(Op, TPN);

    // RegisterOperands are the same thing as RegisterClasses.
    if (OpRec->isSubClassOf("RegisterOperand"))
      OpRec = OpRec->getValueAsDef("RegClass");

    if (OpRec->isSubClassOf("Operand")) {
      if (OpInfo->OperandType == "OPERAND_IMMEDIATE") {
        Op.Opcode = "DCINS::CONSTANT_OP";
      } else {
        Op.Opcode = "DCINS::CUSTOM_OP";
        Op.addOperand(CGI.Namespace + "::OpTypes::" + OpRec->getName());
        auto It = OperandByName.find(OpInfo->Name);
        if (It == OperandByName.end()) {
          OperandByName[OpInfo->Name] = CurDefNo;
        } else {
          // If we already found it, no need to generate the operation again.
          Parent->addOperand(utostr(It->getValue()));
          return;
        }
      }
    } else if (OpRec->isSubClassOf("RegisterClass")) {
      Op.Opcode = "DCINS::GET_RC";
    } else {
      llvm_unreachable("Unknown operand type");
    }
    Op.addOperand(utostr(OpInfo->MIOperandNo));
    addResOperand(*Parent, Op);
  }

  /// Make node semantics from a leaf pattern:
  /// - if \p TPN is an explicit Register, generate:
  ///     DCINS::GET_REG, <inferred type>, Target::RegName
  /// - if \p TPN is a compile-time constant, generate:
  ///     DCINS::MOV_CONSTANT, <inferred type>, <Constant index>
  ///   The constant index points in an uint64_t array, where all compile-time
  ///   constants are uniqued (so that the semantics array remains unsigned[].)
  ///
  void flattenLeaf(const TreePatternNode *TPN, NodeSemantics *Parent) {
    DefInit *OpDef = dyn_cast<DefInit>(TPN->getLeafValue());

    if (OpDef == nullptr) {
      IntInit *OpInt = cast<IntInit>(TPN->getLeafValue());
      NodeSemantics Mov;
      setNSTypeFromNode(Mov, TPN);
      Mov.Opcode = "DCINS::MOV_CONSTANT";
      unsigned &Idx = Target.ConstantIdx[OpInt->getValue()];
      if (Idx == 0)
        Idx = ++Target.CurConstantIdx;
      Mov.addOperand(utostr(Idx - 1));
      addResOperand(*Parent, Mov);
      return;
    }

    Record *OpRec = OpDef->getDef();
    NodeSemantics Op;
    setNSTypeFromNode(Op, TPN);

    if (OpRec->isSubClassOf("Register")) {
      Op.Opcode = "DCINS::GET_REG";
      Op.addOperand(CGI.Namespace + "::" + OpRec->getName());
    } else {
      llvm_unreachable("Unknown operand type");
    }
    addResOperand(*Parent, Op);
  }

  /// Make an operation for "implicit" nodes, generate:
  ///   DCINS::IMPLICIT, MVT::isVoid, <imp-def'd Target::Register>
  ///
  void flattenImplicit(const TreePatternNode *TPN, NodeSemantics &NS) {
    NS.Opcode = "DCINS::IMPLICIT";
    // FIXME: If TPN had something like getChildren(), we could range-ify this.
    for (unsigned i = 0, e = TPN->getNumChildren(); i != e; ++i)
      NS.addOperand(CGI.Namespace + "::" +
                    TPN->getChild(i)->getLeafValue()->getAsString());
  }

  /// Make node semantics for "set" nodes. For all defined values to be set:
  /// - if the destination is a RegisterClass/RegisterOperand, generate:
  ///     DCINS::PUT_RC, <inferred type>, <MIOperandNo of the reg>, <the value>
  /// - if the destination is an explicit Register, generate:
  ///     DCINS::PUT_REG, <inferred type>, <Target::Register name>, <the value>
  ///
  /// Keep track of the results that were dropped from the SDNode child because
  /// of SDNodeEquiv definitions.
  ///
  void flattenSet(const TreePatternNode *TPN) {
    unsigned NumNodeDefs = TPN->getNumChildren() - 1;
    const TreePatternNode *LastChild = TPN->getChild(TPN->getNumChildren() - 1);

    assert(NumNodeDefs == LastChild->getNumTypes() &&
           "Invalid 'set': last child needs to define all the others.");

    // NS will be thrown away, we just use the def indices of the last child.
    NodeSemantics DummyNS;

    flatten(LastChild, &DummyNS);
    // We count what the child defined, because when replacing equivalent
    // SDNodes, it doesn't define all the children.
    unsigned NumDefs = DummyNS.Operands.size();
    unsigned FirstDefNo = CurDefNo - NumDefs;

    for (unsigned i = 0, e = NumDefs; i != e; ++i) {
      const TreePatternNode *Child = TPN->getChild(i);
      Record *OpRec = cast<DefInit>(TPN->getChild(i)->getLeafValue())->getDef();

      NodeSemantics NS;
      NS.Types.push_back(MVT::isVoid);

      // RegisterOperands are the same thing as RegisterClasses.
      if (OpRec->isSubClassOf("RegisterOperand"))
        OpRec = OpRec->getValueAsDef("RegClass");

      if (OpRec->isSubClassOf("RegisterClass")) {
        const CGIOperandList::OperandInfo *OpInfo =
            getNamedOperand(Child->getName());
        assert(OpInfo && "'set' output operand not found in instruction?");
        NS.Opcode = "DCINS::PUT_RC";
        NS.addOperand(utostr(OpInfo->MIOperandNo));
      } else if (OpRec->isSubClassOf("Register")) {
        NS.Opcode = "DCINS::PUT_REG";
        NS.addOperand(CGI.Namespace + "::" + OpRec->getName());
      }
      NS.addOperand(utostr(FirstDefNo + i));
      addSemantics(NS);
    }

    // Keep track of the registers removed from the target-specific SDNode.
    for (unsigned i = NumDefs, e = NumNodeDefs; i != e; ++i) {
      assert(TPN->getChild(i)->isLeaf() &&
             "Invalid SDNode equivalence: dropped non-leaf node!");
      Record *OpRec = cast<DefInit>(TPN->getChild(i)->getLeafValue())->getDef();
      assert(OpRec->isSubClassOf("Register") &&
             "Dropped SDNode result isn't an imp-def'd register.");
      EliminatedImplicitRegs.insert(OpRec);
    }
  }

  /// Make node semantics from SDNodes, generate:
  ///   <SDNode opcode>, <inferred types>, <value indices for the operands>
  ///
  /// Also, try to make an equivalence between the SDNode's operator and
  /// one with less results, as defined by the SDNodeEquiv tablegen definitions.
  ///
  void flattenSDNode(const TreePatternNode *TPN, NodeSemantics &NS) {
    Record *Operator = TPN->getOperator();
    const SDNodeInfo &SDNI = Target.CGPatterns.getSDNodeInfo(Operator);
    NS.Opcode = SDNI.getEnumName();
    auto EquivIt = Target.SDNodeEquiv.find(Operator);
    if (EquivIt != Target.SDNodeEquiv.end()) {
      Record *EquivNode = EquivIt->second;
      const SDNodeInfo &EquivSDNI = Target.CGPatterns.getSDNodeInfo(EquivNode);
      NS.Opcode = EquivSDNI.getEnumName();
      assert((TPN->getNumTypes() - EquivSDNI.getNumResults()) > 0);
      NS.Types.resize(NS.Types.size() -
                      (TPN->getNumTypes() - EquivSDNI.getNumResults()));
    }
    for (unsigned i = 0, e = TPN->getNumChildren(); i != e; ++i)
      flatten(TPN->getChild(i), &NS);
  }

  /// Make node semantics for the whole tree \p TPN.
  void flatten(const TreePatternNode *TPN, NodeSemantics *Parent) {
    if (const CGIOperandList::OperandInfo *OpInfo =
            getNamedOperand(TPN->getName())) {
      assert(Parent != nullptr && "An operand node was at the top-level?");
      flattenOperand(TPN, Parent, OpInfo);
      return;
    }
    if (TPN->isLeaf()) {
      assert(Parent != nullptr && "A leaf node was at the top-level?");
      flattenLeaf(TPN, Parent);
      return;
    }
    Record *Operator = TPN->getOperator();
    NodeSemantics NS;

    setNSTypeFromNode(NS, TPN);

    if (Operator->getName() == "set") {
      assert(Parent == nullptr && "A 'set' node wasn't at the top-level?");
      flattenSet(TPN);
      return;
    }

    if (Operator->getName() == "implicit") {
      assert(Parent == nullptr &&
             "An 'implicit' node wasn't at the top-level?");
      flattenImplicit(TPN, NS);
    } else if (Operator->isSubClassOf("SDNode")) {
      flattenSDNode(TPN, NS);
    } else {
      llvm_unreachable("Unable to handle operator.");
    }
    if (Parent)
      addResOperand(*Parent, NS);
    else
      addSemantics(NS);
  }

public:
  void flatten(const TreePatternNode *TPN) {
    flatten(TPN, nullptr);

    // For all the implicit register definitions we dropped because of
    // SDNode equivalences, add an 'implicit' node.
    NodeSemantics NS;
    NS.Opcode = "DCINS::IMPLICIT";
    NS.Types.push_back(MVT::isVoid);
    for (Record *ImpReg : EliminatedImplicitRegs) {
      NS.Operands.clear();
      NS.addOperand(CGI.Namespace + "::" + ImpReg->getName());
      I.Semantics.push_back(NS);
    }
  }
};

class SemanticsEmitter {
  typedef std::vector<InstSemantics> InstSemaList;

  InstSemaList InstSemas;

  // List mapping Instruction enum values to indices:
  // - first, index of the semantics in InstSemas
  // - replaced by the start offset in the generated array
  std::vector<unsigned> InstIdx;
  unsigned CurSemaOffset;

  void addInstSemantics(unsigned InstEnumValue, const InstSemantics &Sema);

public:
  SemanticsEmitter(RecordKeeper &Records);

  // run - Output the semantics.
  void run(raw_ostream &OS);

  void ParseSemantics();

  RecordKeeper &Records;
  SemanticsTarget SemaTarget;
  CodeGenDAGPatterns &CGPatterns;
  CodeGenTarget &Target;
};

SemanticsEmitter::SemanticsEmitter(RecordKeeper &Records)
    : InstSemas(), InstIdx(), CurSemaOffset(0), Records(Records),
      SemaTarget(Records), CGPatterns(SemaTarget.CGPatterns),
      Target(SemaTarget.CGTarget) {

  const std::vector<const CodeGenInstruction *> &CGIByEnum =
      Target.getInstructionsByEnumValue();
  InstIdx.resize(CGIByEnum.size());

  // Add dummy semantics.
  addInstSemantics(0, InstSemantics());

  // First, look for Semantics instances.
  ParseSemantics();

  // For the rest, try to use the patterns that are in Instruction instances.
  for (unsigned i = 0, e = CGIByEnum.size(); i != e; ++i) {
    const CodeGenInstruction &CGI = *CGIByEnum[i];
    Record *TheDef = CGI.TheDef;
    const DAGInstruction &DI = CGPatterns.getInstruction(TheDef);
    if (InstIdx[i])
      continue;
    if (DI.getPattern() && !CGI.isCodeGenOnly) {
      addInstSemantics(i, InstSemantics(SemaTarget, CGI, *DI.getPattern()));
    }
  }
}

void SemanticsEmitter::addInstSemantics(unsigned InstEnumValue,
                                        const InstSemantics &Sema) {
  InstIdx[InstEnumValue] = InstSemas.size();
  InstSemas.push_back(Sema);
}

void SemanticsEmitter::ParseSemantics() {
  std::vector<Record *> Instrs = Records.getAllDerivedDefinitions("Semantics");
  const std::vector<const CodeGenInstruction *> &CGIByEnum =
      Target.getInstructionsByEnumValue();

  std::map<Record *, DAGInstruction, LessRecordByID> DAGInsts;
  for (Record *I : Instrs) {
    ListInit *LI = nullptr;

    if (isa<ListInit>(I->getValueInit("Pattern")))
      LI = I->getValueAsListInit("Pattern");

    Record *InstDef = I->getValueAsDef("Inst");

    CodeGenInstruction &CGI = Target.getInstruction(InstDef);
    const DAGInstruction &TheInst = CGPatterns.parseInstructionPattern(
        CGI, LI, DAGInsts, /*CanUseOutputOps=*/true);

    // FIXME: Instead of looking for the instruction *every* time, what about:
    // - iterating on InstructionsByEnumValue, and mapping CGI->Semantics before
    // - adding EnumValue to CGI

    auto It = std::find(CGIByEnum.begin(), CGIByEnum.end(), &CGI);
    assert(It != CGIByEnum.end() && *It == &CGI);

    addInstSemantics(std::distance(CGIByEnum.begin(), It),
                     InstSemantics(SemaTarget, CGI, *TheInst.getPattern()));
  }
}

void SemanticsEmitter::run(raw_ostream &OS) {
  emitSourceFileHeader("Target Instruction Semantics", OS);

  StringRef TGName = Target.getName();
  const std::vector<const CodeGenInstruction *> &CGIByEnum =
      Target.getInstructionsByEnumValue();
  assert(CGIByEnum.size() == InstIdx.size());

  OS << "namespace llvm {\n";

  OS << "namespace " << TGName << " {\n";
  OS << "namespace {\n\n";

  OS << "#ifdef GET_INSTR_SEMA\n";

  OS << "const unsigned InstSemantics[] = {\n";
  OS << "  DCINS::END_OF_INSTRUCTION,\n";
  CurSemaOffset = 1;
  for (unsigned I = 1, E = InstIdx.size(); I != E; ++I) {
    if (InstIdx[I] == 0) // FIXME: why?
      continue;
    InstSemantics &Sema = InstSemas[InstIdx[I]];
    InstIdx[I] = CurSemaOffset++;
    OS << "  // " << CGIByEnum[I]->TheDef->getName() << "\n";
    for (NodeSemantics &NS : Sema.Semantics) {
      ++CurSemaOffset;
      OS.indent(2) << NS.Opcode;
      for (auto &Ty : NS.Types)
        OS << ", " << llvm::getEnumName(Ty);
      CurSemaOffset += NS.Types.size();
      for (auto &Op : NS.Operands)
        OS << ", " << Op;
      CurSemaOffset += NS.Operands.size();
      OS << ",\n";
    }
    OS << "  DCINS::END_OF_INSTRUCTION,\n";
  }
  OS << "};\n\n";

  OS << "const unsigned OpcodeToSemaIdx[] = {\n";
  for (unsigned I = 0, E = InstIdx.size(); I != E; ++I)
    OS << InstIdx[I] << ", \t// " << CGIByEnum[I]->TheDef->getName() << "\n";
  OS << "};\n\n";

  assert(SemaTarget.CurConstantIdx == SemaTarget.ConstantIdx.size());
  std::vector<uint64_t> Constants(SemaTarget.CurConstantIdx);
  for (auto &CI : SemaTarget.ConstantIdx)
    Constants[CI.second - 1] = CI.first;
  OS << "const uint64_t ConstantArray[] = {\n";
  for (uint64_t Constant : Constants)
    OS.indent(2) << Constant << "ULL,\n";
  OS << "};\n\n";

  OS << "#endif // GET_INSTR_SEMA\n";

  OS << "#ifdef GET_REGISTER_SEMA\n";

  // FIXME: Also generate the rest of DCRegisterSema here
  OS << "const MVT::SimpleValueType RegClassVTs[] = {\n";
  const std::list<CodeGenRegisterClass> RCs =
      Target.getRegBank().getRegClasses();
  std::vector<const CodeGenRegisterClass*> RCByEnumValue(RCs.size());
  for (auto &RC : RCs)
    RCByEnumValue[RC.EnumValue] = &RC;
  for (auto *RC : RCByEnumValue) {
    MVT::SimpleValueType VT = RC->VTs[0];
    if (VT == MVT::x86mmx)
      VT = MVT::i64;
    OS.indent(2) << llvm::getName(VT) << ", // " << RC->getName() << " \n";
  }
  OS << "};\n\n";
  OS << "#endif // GET_REGISTER_SEMA\n";

  OS << "\n} // end anonymous namespace\n";
  OS << "} // end namespace " << TGName << "\n";
  OS << "} // end namespace llvm\n";
}

} // end anonymous namespace

SemanticsTarget::SemanticsTarget(RecordKeeper &Records)
    : Records(Records), CGPatterns(Records),
      CGTarget(CGPatterns.getTargetInfo()), SDNodeEquiv(), ConstantIdx(),
      CurConstantIdx(0) {
  for (Record *Equiv : Records.getAllDerivedDefinitions("SDNodeEquiv"))
    SDNodeEquiv[Equiv->getValueAsDef("TargetSpecific")] =
        Equiv->getValueAsDef("TargetIndependent");
}

InstSemantics::InstSemantics(SemanticsTarget &Target,
                             const CodeGenInstruction &CGI,
                             const TreePattern &TP) {
  Flattener Flat(Target, CGI, *this);
  for (TreePatternNode *TPN : TP.getTrees())
    Flat.flatten(TPN);
}

InstSemantics::InstSemantics() {
  NodeSemantics NS;
  NS.Opcode = "DCINS::END_OF_INSTRUCTION";
  Semantics.push_back(NS);
}

namespace llvm {

bool EmitSemantics(RecordKeeper &Records, raw_ostream &OS) {
  SemanticsEmitter(Records).run(OS);
  return false;
}

} // end namespace llvm
